# Generated by Django 3.2 on 2021-08-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Korildi'),
        ),
    ]
