# Generated by Django 3.2 on 2021-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='body',
            field=models.CharField(max_length=300, verbose_name='Text'),
        ),
    ]
